# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

   # Bootloader.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";
  boot.loader.grub.useOSProber = true;

  boot.initrd.luks.devices."luks-27cc08a3-261e-4da1-beae-1fe9a61f57ef".device = "/dev/disk/by-uuid/27cc08a3-261e-4da1-beae-1fe9a61f57ef";
  # Setup keyfile
  boot.initrd.secrets = {
    "/boot/crypto_keyfile.bin" = null;
  };

  boot.loader.grub.enableCryptodisk = true;

  boot.initrd.luks.devices."luks-6f53bc66-23d8-4c65-aeb0-ce8775b1552c".keyFile = "/boot/crypto_keyfile.bin";
  boot.initrd.luks.devices."luks-27cc08a3-261e-4da1-beae-1fe9a61f57ef".keyFile = "/boot/crypto_keyfile.bin";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6be0b367-cd67-468c-8792-4e53dc357244";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6f53bc66-23d8-4c65-aeb0-ce8775b1552c".device = "/dev/disk/by-uuid/6f53bc66-23d8-4c65-aeb0-ce8775b1552c";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a3d42fd4-40f7-4d88-a932-fa0439a96f70"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wls3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
