# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
    config,
    lib,
    pkgs,
    ...
}:
let
    intelGPU = "56a5";
in
{

    hardware.enableRedistributableFirmware = true;

    # Bootloader.
    boot.loader.systemd-boot = {
        enable = true;
        configurationLimit = 10;
    };
    boot.loader.efi.canTouchEfiVariables = true;

    nix.settings.max-jobs = 4; # set to core count w/o hyprethreading to not choke other services
    nix.settings.cores = 1; # really make sure nix doesn't get greedy with cores on a rebuild

    boot.initrd.availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
    ];
    boot.initrd.kernelModules = [ ];
    #boot.kernelPackages = pkgs.linuxPackages_latest;
    boot.kernelPackages = pkgs.linuxPackages_6_12;
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    boot.kernelParams = [
        "i915.force_probe=!${intelGPU}"
        "xe.force_probe=${intelGPU}"
    ];

    fileSystems."/" = {
        device = "/dev/disk/by-uuid/0b6a9c0b-6606-479b-8500-843fb2102c8d";
        fsType = "ext4";
        options = [
            "noatime"
            "nodiratime"
            "discard"
        ];
    };

    fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/3556-44E1";
        fsType = "vfat";
        options = [
            "fmask=0077"
            "dmask=0077"
        ];
    };

    fileSystems."/mnt/cache" = {
        device = "/dev/disk/by-uuid/a63ca719-268e-476e-b28d-252dcbeaaa04";
        fsType = "ext4";
        options = [
            "noatime"
            "nodiratime"
            "discard"
        ];
    };

    swapDevices = [
        { device = "/dev/disk/by-uuid/290e7047-d429-4196-825d-8fd6cc01d7d5"; }
    ];

    # Intel ARC GPU
    hardware.graphics.extraPackages = [ pkgs.vpl-gpu-rt ];
    environment.systemPackages = with pkgs; [
        intel-gpu-tools
    ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    nixpkgs.system = "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
